### ISSUE TITLE
英文の間違いや表記ゆれを修正する

### ISSUE THREAD

**Issue by HidegonSan** [yak9909/AnimalBytes#24]
## `README.md` の英文の間違いです。
* `It's good` のあとのピリオドが抜けています。
* `if you using` ではなく `If you are using` ではないでしょうか？
* `download installer` ではなく `download the installer` ではないでしょうか？
* `write IP` ではなく `write the IP` ではないでしょうか？

## `README.md` の提案です。
`make -j` ではなく `git clone https://github.com/yak9909/AnimalBytes && cd AnimalBytes && make` の方が良いのではないでしょうか？

## ファイル名に関する提案です。
`auto_drop.cpp` と `PocketItem.cpp` のように命名規則の混在を無くすべきではないでしょうか。  
以下は、ファイル名がスネークケースで記載されているものです。  
```
Sources/Cheats/ItemDrops/auto_drop.cpp
Sources/Cheats/ItemDrops/item_changer.cpp
Sources/Cheats/TextToCheats/command_funcs.cpp
Sources/Cheats/TextToCheats/find_items.cpp
Sources/Cheats/TextToCheats/text_to_item.cpp
Sources/Cheats/make_folder.cpp
Sources/hook_func.s
Sources/init_hooks.cpp
```

## 変数などの命名規則、並びに誤字に関する提案です。
こちらも同様に、表記ゆれが見受けられます。 どちらか一方に統一するべきだと思います。  
`Includes/ACNL/Address/Chat.h` 5行目 `BufferPointer`  
`Includes/ACNL/Address/Chat.h` 6行目 `TextLengthPointer`  
`Includes/ACNL/Address/Chat.h` 7行目 `IsSent`  
`Includes/ACNL/Address/Data.h` 5行目 `ItemNameBase`  
`Includes/ACNL/Player.h` 10行目 `static int WriteItem`  
`Includes/ACNL/Player.h` 27行目 `static u32 ReadItem`  
`Includes/Cheats/CodeContext.h` 7行目 `bool f_coordmod`  
`Includes/Cheats/CodeContext.h` 8行目 `bool f_autodrop`  
`Includes/Cheats/SpeedHack.h` 8行目 `void speedhackmenu`  
`Includes/Cheats/SpeedHack.h` 10行目 `void gamespeed_boost`  
`Includes/DevUtils/ViewerEx.h` 11行目 `static void gamefunc`  
`Includes/DevUtils/ViewerEx.h` 12行目 `static void menufunc`  
`Includes/Helpers/AutoRegion.h` 21行目 `const u32 Usa;`  
`Includes/Helpers/AutoRegion.h` 22行目 `const u32 Eur;`  
`Includes/Helpers/Converter.h` 7行目 `std::vector<int> hexnumbers_to_dec`  
`Includes/Helpers/InstantMenu.h` 70行目 `static constexpr int tickmax`  
`Includes/Helpers/Logger.h` 21行目 `Logger(std::string const& path)`  
`Includes/Helpers/StringType.h` 16行目 `StringType get_strtype`  
`Includes/Cheats.h` 14行目 `AutoDrop`  
`Includes/Cheats.h` 15行目 `ItemChanger`  
`Sources/ACNL/Game.cpp` 11行目 `ItemInfo const AllItems`  
`Sources/ACNL/Chat.cpp` 51行目 `u32 lengthptr;`  
`Sources/ACNL/Game.cpp` 241行目 `std::string isDead`  
`Sources/Cheats/ItemDrops/auto_drop.cpp` 19行目 `auto& ctxdrop = ctx->c_autodrop;`  
`Sources/Cheats/ItemDrops/auto_drop.cpp` 37行目 `ctx->c_dropcheats.drop`  
`Sources/Cheats/ItemDrops/item_changer.cpp` 13行目 `constexpr int canChangeItemID`  
`Sources/Cheats/ItemDrops/item_changer.cpp` 25行目 `// drawed`  
`Sources/Cheats/ItemDrops/item_changer.cpp` 31行目 `ctx->c_dropcheats.item;`  
`Sources/Cheats/Items/PocketItem.cpp` 9行目 `u32 itemid;`  
`Sources/Cheats/SpeedHacks/SpeedHackMenu.cpp` 10行目 `std::vector<u32> Adresses;`  
`Sources/Cheats/TextToCheats/find_items.cpp` 14行目 `static auto adjustStr`  
`Sources/Cheats/TextToCheats/text_to_item.cpp` 12行目 `#define ctox`  
`Sources/init_hooks.cpp` 14行目 `static constexpr u32 asmjump`  
`Sources/init_hooks.cpp` 18行目 `static Mutex MemoryMutex;`  
`Sources/init_hooks.cpp` 19行目 `static std::vector<MemInfo> MemRegions;`  
`Sources/init_hooks.cpp` 28行目 `static std::vector<OSDMessage*> Notifications;`  
`Sources/init_hooks.cpp` 37行目 `static bool c_Process_CheckAddress`  
`Sources/init_hooks.cpp` 43行目 `const& memInfo`  
`Sources/init_hooks.cpp` 55行目 `InitHooks`  
`Sources/main.cpp` 15行目 `HIDE810 (Debuggings)`

**Comment by HIDE810** [comment]
They'll be improved as needed in the future.
Please send a pull request if you care about them.
